services:
  db:
    image: mysql:8.4
    restart: always
    env_file:
      - ./mysql.env
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    restart: always
    depends_on:
      - db
    env_file:
      - ./phpmyadmin.env
    ports:
      - "8080:80"
